# version: '3.8'

# services:
#   # База данных для продукта
#   product-db:
#     image: postgres:13
#     container_name: product-db
#     environment:
#       POSTGRES_DB: products
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 8228
#     ports:
#       - "5432:5432"
#     volumes:
#       - product_db_data:/var/lib/postgresql/data

#   # База данных для пользователей
#   user-db:
#     image: postgres:13
#     container_name: user-db
#     environment:
#       POSTGRES_DB: db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: 8228
#     ports:
#       - "5433:5432"
#     volumes:
#       - user_db_data:/var/lib/postgresql/data

#   # Product Service
#   product-service:
#     build: ./backend/product
#     container_name: product-service
#     ports:
#       - "8081:8081"
#     environment:
#       SPRING_PROFILES_ACTIVE: docker
#     depends_on:
#       - product-db
#     restart: on-failure

#   # User Service
#   user-service:
#     build: ./backend/rest
#     container_name: user-service
#     ports:
#       - "8080:8080"
#     environment:
#       SPRING_PROFILES_ACTIVE: docker
#     depends_on:
#       - user-db
#     restart: on-failure

# volumes:
#   product_db_data:
#   user_db_data:


services:
  # -------------------- PRODUCT DATABASE --------------------
  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8228
    volumes:
      - ./product/init.sql:/docker-entrypoint-initdb.d/init.sql
      - product_data:/var/lib/postgresql/data
    networks:
      - avito-net

  # -------------------- USER DATABASE -----------------------
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8228
    volumes:
      - ./rest/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user_data:/var/lib/postgresql/data
    networks:
      - avito-net

  # -------------------- PRODUCT SERVICE ---------------------
  product-service:
    build: ./product
    depends_on:
      - product-db
    ports:
      - "8081:8081"
    networks:
      - avito-net

  # -------------------- USER SERVICE ------------------------
  user-service:
    build: ./rest
    depends_on:
      - user-db
    ports:
      - "8080:8080"
    networks:
      - avito-net

volumes:
  product_data:
  user_data:

networks:
  avito-net: