services:
  # -------------------- PRODUCT DATABASE --------------------
  product-db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8228
    volumes:
      - ./product/init.sql:/docker-entrypoint-initdb.d/init.sql
      - product_data:/var/lib/postgresql/data
    networks:
      - avito-net

  # -------------------- USER DATABASE -----------------------
  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8228
    volumes:
      - ./rest/init.sql:/docker-entrypoint-initdb.d/init.sql
      - user_data:/var/lib/postgresql/data
    networks:
      - avito-net

  # -------------------- PRODUCT SERVICE ---------------------
  product-service:
    build: ./product
    depends_on:
      - product-db
    ports:
      - "8081:8081"
    networks:
      - avito-net

  # -------------------- USER SERVICE ------------------------
  user-service:
    build: ./rest
    depends_on:
      - user-db
    ports:
      - "8080:8080"
    networks:
      - avito-net

volumes:
  product_data:
  user_data:

networks:
  avito-net: