server:
    port:
        8180

spring:
    application:
        name: "gateway-service"

    cloud:
        gateway:
            public-paths:
              - /auth/signin
              - /auth/signup
              - /auth/refresh
              
            server:
                webflux:
                    routes:
                      - id: auth-service
                        uri: http://localhost:8081
                        predicates:
                            - Path=/auth/**

                      - id: user-service
                        uri: http://localhost:8082
                        predicates:
                            - Path=/users/**

                      - id: product-service
                        uri: http://localhost:8083
                        predicates:
                            - Path=/products/**

jwt:
    public-path: classpath:jwt/public.pem